---
- name: Copy /etc/shadow to nodes
  hosts: all
  become: yes

  vars:
    file: '/etc/shadow'

  tasks:
    - name: Copying /etc/shadow
      copy:
        src: "{{ file }}"
        dest: "{{ file }}"