---
# tasks file for nfs-server

- name: Ensure NFS server is started and enabled at boot
  service:
    name: nfs-server
    state: reloaded
    enabled: yes
      
- name: Copy exports template to /etc/exports
  template:
    src: templates/exports.j2
    dest: /etc/exports
  notify: Restart NFS server


- name: permit traffic in default zone for nfs service
  ansible.posix.firewalld:
    service: nfs
    permanent: yes
    state: enabled

- name: permit traffic in default zone for mountd service
  ansible.posix.firewalld:
    service: mountd
    permanent: yes
    state: enabled

- name: permit traffic in default zone for rpc-bind service
  ansible.posix.firewalld:
    service: rpc-bind
    permanent: yes
    state: enabled

- name: Roloading Firewalld
  ansible.builtin.command: sudo firewall-cmd --reload


#- name: Copy /home/vagrant (montoxo) dir to NFS server
#  ansible.builtin.copy:
#    src: "root@{{ montoxo_ip }}:{{ vagrant_path }}"
#    dest: "{{ vagrant_path }}"
#    remote_src: yes

- name: Copy /home/vagrant (montoxo) dir to NFS server
  ansible.builtin.command: "sshpass -p {{ montoxo_passwd }} scp -r root@{{ montoxo_ip }}:{{ vagrant_path }} /home"

- name: Add Pubkey to it's own authorized_keys
  shell: 
    cmd: 'cat /home/{{ item }}/.ssh/id_rsa.pub >> /home/{{ item }}/.ssh/authorized_keys'
  loop: "{{ users_name_list }}" 


#- name: Add Pubkey to it's own authorized_keys
#  ansible.posix.authorized_key:
#    user: "{{ item }}"
#    state: present
#    key: "{{ lookup('file', '/home/{{ item }}/.ssh/id_rsa.pub') }}"
#  loop: "{{ users_name_list }}"     