---
# tasks file for nfs-client
- name: Mount NFS share
  mount:
    path: "{{ nfs_dir }}"
    src: "{{ nfs_server}}:{{ nfs_dir }}"
    fstype: nfs
    state: mounted

- name: Enable NTP synchronization.
  ansible.builtin.command: timedatectl set-ntp true    


- name: Copy CGroup Slurm Configuartion File
  ansible.builtin.copy:
    src: /vagrant/Provisioning/slurm_config/cgroup.conf
    dest: /etc/slurm/cgroup.conf 


- name: Copy Slurm Configuartion File
  template:
    src: /vagrant/Provisioning/slurm_config/slurm.conf.j2
    dest: /etc/slurm/slurm.conf
 

- name: Restart service Slurmctl, if not started
  ansible.builtin.service:
    name: slurmctld
    state: restarted
    enabled: yes

- name: Restart service Slurmdbd, if not started
  ansible.builtin.service:
    name: slurmdbd
    state: restarted
    enabled: yes

- name: Restart service Munge
  ansible.builtin.service:
    name: munge
    state: restarted
    enabled: yes
 
- name: Remove from Public Zone eth1
  ansible.builtin.command: firewall-cmd --permanent --zone=public --remove-interface=eth1

#- name: Remove from Public Zone eth1
#  ansible.posix.firewalld:
#    zone: public
#    interface: eth1
#    permanent: true
#    immediate: true
#    state: disabled

- name: Add eth1 to trusted Zone
  ansible.builtin.command: firewall-cmd --zone=trusted --change-interface=eth1 --permanent

#- name: Add eth1 to trusted Zone
#  ansible.posix.firewalld:
#    zone: trusted
#    interface: eth1
#    permanent: true
#    immediate: true
#    state: enabled

- name: Roloading Firewalld
  ansible.builtin.command: sudo firewall-cmd --reload    


- name: Installing OHPC modules
  dnf:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - ohpc-autotools
      - gnu12-compilers-ohpc
      - gnu9-compilers-ohpc
      - openmpi4-gnu12-ohpc
      - openmpi4-gnu9-ohpc
      - mvapich2-gnu12-ohpc
      - ohpc-gnu12-perf-tools
      - hwloc-ohpc
      - lmod-ohpc


- name: Copy /etc/resolv.conf file
  ansible.builtin.copy:
    src: /vagrant/Provisioning/resolv_config/resolv.conf
    dest: /etc/resolv.conf
