---
# tasks file for nfs-client
- name: Mount NFS share
  mount:
    path: "{{ nfs_dir }}"
    src: "{{ nfs_server}}:{{ nfs_dir }}"
    fstype: nfs
    state: mounted

- name: Enable NTP synchronization.
  ansible.builtin.command: timedatectl set-ntp true    


- name: Copy CGroup Slurm Configuartion File
  ansible.builtin.copy:
    src: /vagrant/Provisioning/slurm_config/cgroup.conf
    dest: /etc/slurm/cgroup.conf 


- name: Copy Slurm Configuartion File
  template:
    src: /vagrant/Provisioning/slurm_config/slurm.conf.j2
    dest: /etc/slurm/slurm.conf
 

- name: Restart service Slurmctl, if not started
  ansible.builtin.service:
    name: slurmctld
    state: restarted
    enabled: yes

- name: Restart service Slurmdbd, if not started
  ansible.builtin.service:
    name: slurmdbd
    state: restarted
    enabled: yes

- name: Restart service Munge
  ansible.builtin.service:
    name: munge
    state: restarted
    enabled: yes
 
- name: Remove from Public Zone eth1
  ansible.builtin.command: firewall-cmd --permanent --zone=public --remove-interface=eth1

#- name: Remove from Public Zone eth1
#  ansible.posix.firewalld:
#    zone: public
#    interface: eth1
#    permanent: true
#    immediate: true
#    state: disabled

- name: Add eth1 to trusted Zone
  ansible.builtin.command: firewall-cmd --zone=trusted --change-interface=eth1 --permanent

#- name: Add eth1 to trusted Zone
#  ansible.posix.firewalld:
#    zone: trusted
#    interface: eth1
#    permanent: true
#    immediate: true
#    state: enabled

- name: Roloading Firewalld
  ansible.builtin.command: sudo firewall-cmd --reload    


- name: Adding Docker repo
  ansible.builtin.command: sudo dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Installing Prometheus in ansible
  ansible.builtin.command: sudo ansible-galaxy collection install prometheus.prometheus

- name: Installing OHPC and Docker modules
  dnf:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - ohpc-autotools
      - gnu12-compilers-ohpc
      - gnu9-compilers-ohpc
      - openmpi4-gnu12-ohpc
      - openmpi4-gnu9-ohpc
      - mvapich2-gnu12-ohpc
      - ohpc-gnu12-perf-tools
      - hwloc-ohpc
      - lmod-ohpc
      - mpich-ucx-gnu12-ohpc
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin 
      - docker-compose-plugin

- name: Copy /etc/resolv.conf file
  ansible.builtin.copy:
    src: /vagrant/Provisioning/resolv_config/resolv.conf
    dest: /etc/resolv.conf


- name: Restart Docker service 
  ansible.builtin.service:
    name: docker
    state: restarted
    enabled: yes

- name: Create a Prometheus directory if it does not exist
  ansible.builtin.file:
    path: /root/prometheus/config/
    state: directory
    mode: '0755'

- name: Copying prometheus.yml
  ansible.builtin.copy:
    src: /vagrant/Provisioning/Docker/montoxo/prometheus_config/prometheus.yml
    dest: /root/prometheus/config/prometheus.yml

- name: Copying node_rules.yml
  ansible.builtin.copy:
    src: /vagrant/Provisioning/Docker/montoxo/prometheus_config/node_rules.yaml
    dest: /root/prometheus/config/node_rules.yaml

- name: Copying compose.yml
  ansible.builtin.copy:
    src: /vagrant/Provisioning/Docker/montoxo/compose.yaml
    dest: /root/compose.yml

- name: Copying Grafana Config
  copy:
    src: /vagrant/Provisioning/Docker/montoxo/grafana_config
    dest: /root/prometheus/config