# Variables for settings.yaml
variables:
  # openssl passwd -1 vagrant
  DEFAULT_PASSWD : "$1$C8wD.d/N$4df2/5cyim7XYDXeOAOob0"
  MANAGE_DHCP: true
  MANAGE_DHCP_V4: true
  MANAGE_DHCP_V6: true
  NEXT_SERVER_V4: 192.168.1.2
  NEXT_SERVER_V6: ::ffff:c0a8:102
  SERVER: 192.168.1.2
  IPXE_VAR: true