# Variables for settings.yaml
variables:
  # openssl passwd -1 vagrant
  DEFAULT_PASSWD : "$1$C8wD.d/N$4df2/5cyim7XYDXeOAOob0"
  MANAGE_DHCP: true
  MANAGE_DHCP_V4: true
  NEXT_SERVER_V4: 192.168.56.27
  SERVER : 192.168.56.27

  