---
# tasks file for compute_nodes

- name: Mount NFS share
  mount:
    path: "{{ nfs_dir }}"
    src: "{{ nfs_server}}:{{ nfs_dir }}"
    fstype: nfs
    state: mounted

- name: Enable NTP synchronization.
  ansible.builtin.command: timedatectl set-ntp true 

- name: Install OpenHPC repo 
  ansible.builtin.command: yum install -y http://repos.openhpc.community/OpenHPC/2/EL_8/x86_64/ohpc-release-2-1.el8.x86_64.rpm

- name: Start service Chronyd, if not started
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: yes

- name: Copy Chrony Server Configuartion File
  ansible.builtin.copy:
    src: /vagrant/Provisioning/chrony_config/client/chrony.conf
    dest: /etc/chrony.conf

- name: Restart service Chronyd
  ansible.builtin.service:
    name: chronyd
    state: restarted
    enabled: yes    

- name: Install the latest version of OHPC-Slurm-Client
  ansible.builtin.dnf:
    name: ohpc-slurm-client
    state: latest

- name: Enable ssh control via resource manager Slurm
  ansible.builtin.lineinfile: 
    path: /etc/pam.d/sshd
    line: -account required pam_slurm_adopt.so


- name: Copy CGroup Slurm Configuartion File
  ansible.builtin.copy:
    src: /vagrant/Provisioning/slurm_config/cgroup.conf
    dest: /etc/slurm/cgroup.conf 


- name: Copy Slurm Configuartion File
  template:
    src: /vagrant/Provisioning/slurm_config/slurm.conf.j2
    dest: /etc/slurm/slurm.conf  

- name: Copy munge.key from montoxo
  shell: 
    cmd: 'sshpass -p {{ montoxo_passwd }} scp -o StrictHostKeyChecking=no root@{{ front_node }}:/etc/munge/munge.key /etc/munge/munge.key'

- name: Restart service Slurmd, if not started
  ansible.builtin.service:
    name: slurmd
    state: restarted
    enabled: yes

- name: Restart service Munge
  ansible.builtin.service:
    name: munge
    state: restarted
    enabled: yes

- name: Stop and disable firewalld.
  service:
    name: firewalld
    state: stopped
    enabled: False

- name: Enable Powertools.
  ansible.builtin.command: dnf config-manager --set-enabled powertools

- name: Installing OHPC modules
  dnf:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - ohpc-autotools
      - gnu12-compilers-ohpc
      - gnu9-compilers-ohpc
      - openmpi4-gnu12-ohpc
      - openmpi4-gnu9-ohpc
      - mvapich2-gnu12-ohpc
      - ohpc-gnu12-perf-tools
      - hwloc-ohpc
      - lmod-ohpc
      - mpich-ucx-gnu12-ohpc
