---
# tasks file for users_config

- name: Update SO 
  ansible.builtin.command: sudo dnf update -y

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled

- name: Create Usuarios Group
  ansible.builtin.group:
    name: "{{ group_name }}"
    state: present

- name: Create Vagrant User
  user:
   name: "{{ vagrant_user }}"
   group: "{{ group_name }}"
   append: true
   shell: /bin/bash
   create_home: true
  register: accounts    

- name: Installing List of Packages By DNF 
  dnf:
    name: "{{ packages }}"
    state: latest
  vars:
    packages: 
      - httpd
      - tree
      - nano
      - nfs-utils
      - cifs-utils
      - sshpass
      - chrony

- name: Set timezone to Europe/Madrid
  community.general.timezone:
    name: Europe/Madrid
