---
# tasks file for users_config

- name: Update SO 
  ansible.builtin.command: sudo dnf update -y

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled

- name: Create Usuarios Group
  ansible.builtin.group:
    name: "{{ group_name }}"
    state: present

- name: Create Vagrant User
  user:
   name: "{{ vagrant_user }}"
   group: "{{ group_name }}"
   append: true
   shell: /bin/bash
   create_home: true
  register: accounts    

- name: Installing List of Packages By DNF 
  dnf:
    name: "{{ packages }}"
    state: latest
  vars:
    packages: 
      - httpd
      - tree
      - nano
      - nfs-utils
      - cifs-utils
      - sshpass
      - chrony

- name: Set timezone to Europe/Madrid
  community.general.timezone:
    name: Europe/Madrid

- name: Install OpenHPC repo 
  ansible.builtin.command: yum install -y http://repos.openhpc.community/OpenHPC/2/EL_8/x86_64/ohpc-release-2-1.el8.x86_64.rpm

- name: Restart service Slurmd, if not started
  ansible.builtin.service:
    name: slurmd
    state: restarted
    enabled: yes

- name: Restart service Munge, if not started
  ansible.builtin.service:
    name: munge
    state: restarted
    enabled: yes  