---
# tasks file for montoxo_config
- name: Create Users
  user:
   name: "{{ item }}"
   group: "{{ group_name }}"
   append: true
   shell: /bin/bash
   create_home: true
   password: "{{ 'abc123' | password_hash('sha512', 'mysecretsalt') }}"
   update_password: on_create
   generate_ssh_key: yes
   ssh_key_bits: 2048
   ssh_key_file: .ssh/id_rsa
  loop: "{{ users_name_list }}" 
  register: accounts
  notify: force change password

#- name: Copying Sergio PubKey
#  ansible.builtin.command: sh /vagrant/pub_script/cp_pub_script.sh

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /home/vagrant
    owner: vagrant
    group: Usuarios
    recurse: yes

- name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
  openssh_keypair:
    path: /home/vagrant/.ssh/id_rsa
    owner: "{{ vagrant_user }}"
    group: "{{ group_name }}"


- name: Install OpenHPC repo 
  ansible.builtin.command: yum install -y http://repos.openhpc.community/OpenHPC/2/EL_8/x86_64/ohpc-release-2-1.el8.x86_64.rpm

- name: Start service Chronyd, if not started
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: yes

- name: Copy Chrony Server Configuartion File
  ansible.builtin.copy:
    src: /vagrant/Provisioning/chrony_config/server/chrony.conf
    dest: /etc/chrony.conf

- name: Restart service Chronyd
  ansible.builtin.service:
    name: chronyd
    state: restarted
    enabled: yes

- name: Install the latest version of OHPC-Slurm-Server
  ansible.builtin.dnf:
    name: ohpc-slurm-server
    state: latest

- name: Installing Prometheus in ansible
  ansible.builtin.command: sudo ansible-galaxy collection install prometheus.prometheus


- name: Copying node_exporter role to /etc/ansible/roles
  ansible.builtin.copy:
    src: /root/.ansible/collections/ansible_collections/prometheus/prometheus/roles/node_exporter
    dest: /etc/ansible/roles/