---
# tasks file for nodes_config
- name: Create Users
  user:
   name: "{{ item }}"
   group: "{{ group_name }}"
   append: true
   shell: /bin/bash
   create_home: true
   password: "{{ 'abc123' | password_hash('sha512', 'mysecretsalt') }}"
   update_password: on_create
   generate_ssh_key: yes
   ssh_key_bits: 2048
   ssh_key_file: .ssh/id_rsa
  loop: "{{ users_name_list }}" 
  register: accounts

- name: Change permissions to /usr/bin/passwd
  ansible.builtin.file:
    path: /usr/bin/passwd
    mode: '700'

- name: Add montoxo.dec.udc.es pubkey
  shell: 
    cmd: 'sshpass -p vagrant123 ssh -o StrictHostKeyChecking=no root@192.168.0.17 cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys'

#- name: Run a script to add montoxo.dec.udc.es pubkey
#  ansible.builtin.script: files/montoxo_pub_copy.sh

- name: Enable Powertools.
  ansible.builtin.command: dnf config-manager --set-enabled powertools


- name: Installing Prometheus in ansible
  ansible.builtin.command: sudo ansible-galaxy collection install prometheus.prometheus

#- name: Copy prometheus.yml
#  ansible.builtin.copy:
#    src: /vagrant/Provisioning/Prometheus/nodes/node_exporter.yml
#    dest: /root/node_exporter.yml

#- name: Ansible prometheus role
#  ansible.builtin.galaxy:
#    name: prometheus.prometheus

- name: Add Lang packages
  package:
    name: glibc-langpack-en
    state: present

- name: localectl
  ansible.builtin.command: localectl set-locale LANG=en_US.UTF-8

#- name: Execute node_exporter
#  ansible.builtin.include_role:
#    name: prometheus.prometheus.node_exporter
  
- name: Execute node_exporter
  ansible.builtin.command: ansible-playbook /root/node_exporter.yml