- name: Download Puppet6
  ansible.builtin.command: sudo dnf -y install https://yum.puppet.com/puppet6-release-el-8.noarch.rpm

- name: Download TheForeman
  ansible.builtin.command: sudo dnf -y install https://yum.theforeman.org/releases/2.5/el8/x86_64/foreman-release.rpm

- name: Reset Ruby
  ansible.builtin.command: sudo dnf module reset ruby -y

- name: Enable Ruby
  ansible.builtin.command: sudo dnf -y module enable ruby:2.7

- name: Update Rocky
  ansible.builtin.command: sudo dnf update -y

- name: Installing List of Packages By DNF 
  dnf:
    name: "{{ packages }}"
    state: latest
  vars:
    packages: 
      - foreman-installer
      - glibc-locale-source
      - nano
      - chrony
      - ruby

- name: Set Timezone
  ansible.builtin.command: sudo timedatectl set-timezone Europe/Madrid   

- name: Set Hostname
  ansible.builtin.command: sudo hostnamectl set-hostname foreman.server.com  

#- name: Installing Foreman
#  ansible.builtin.command: sudo foreman-installer
