
- name: Installing List of Packages By Package Module
  ansible.builtin.package:
    name: 
      - httpd
      - git
      - openssl
    state: latest 

- name: Enable DNF Cobbler Module
  ansible.builtin.command: sudo dnf module enable cobbler:3.3 -y

- name: Installing List of Packages By DNF 
  dnf:
    name: "{{ packages }}"
    state: latest
  vars:
    packages: 
      - nano
      - unzip
      - cobbler
      - dnsmasq
      - syslinux
      - pykickstart
      - xinetd
      - tftp
      - dhcp-server
      - fence-agents
      - debmirror

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled


